version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo_network

  # Laravel Backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: todo_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./server:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=todo_app
      - DB_USERNAME=todo_user
      - DB_PASSWORD=todo_password
    depends_on:
      - mysql
    networks:
      - todo_network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.git
    environment:
      - REACT_APP_API_URL=http://backend:8000/graphql
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - todo_network

volumes:
  mysql_data:

networks:
  todo_network:
    driver: bridge 